on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: 'Name of Resource Group to Deploy into.'
        default: 'Skyline-Secure'
        required: true
      azWebAppName:
        description: 'Name of app being deployed to AKS.'
        default: 'mvcwebapp'
        required: true
      azWebAPIName:
        description: 'Name of web api being deployed to AKS.'
        default: 'webapi'
        required: true
name: webapp-build-push-acr-secure
env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME_SECURE }}
  WEB_APP_NAME: ${{ github.event.inputs.azWebAppName }}
  WEB_API_NAME: ${{ github.event.inputs.azWebAPIName }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    # Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME_SECURE }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME_SECURE }}
        password: ${{ secrets.REGISTRY_PASSWORD_SECURE }}
    # Container build and push to a Azure Container Registry (ACR)
    - run: |
        cd MvcWebApp
        pwd
        ls -l
        echo $template

        docker build . -t ${{ secrets.REGISTRY_NAME_SECURE }}.azurecr.io/${{ env.WEB_APP_NAME }}:latest
        docker push ${{ secrets.REGISTRY_NAME_SECURE }}.azurecr.io/${{ env.WEB_APP_NAME }}:latest

        cd ../WebAPI
        pwd
        ls -l
        docker build . -t ${{ secrets.REGISTRY_NAME_SECURE }}.azurecr.io/${{ env.WEB_API_NAME }}:latest
        docker push ${{ secrets.REGISTRY_NAME_SECURE }}.azurecr.io/${{ env.WEB_API_NAME }}:latest